#############################################################################
# Makefile for building: libDcRawQT.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.6.1) on: Sat Apr 10 09:30:28 2010
# Project:  DcRawQT.pro
# Template: lib
# Command: /opt/qtsdk-2010.01/qt/bin/qmake -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile DcRawQT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDCRAWQT_LIBRARY -D__MINGW__ -DNO_JPEG -DUSE_CIMG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.01/qt/include/QtCore -I/opt/qtsdk-2010.01/qt/include/QtGui -I/opt/qtsdk-2010.01/qt/include -I../CImg -I/usr/local/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.01/qt/lib -shared -Wl,-soname,libDcRawQT.so.1
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.01/qt/lib -L/usr/local/lib -llcms -lQtGui -L/opt/qtsdk-2010.01/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.01/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dcrawqt.cpp \
		dcraw.cpp \
		dcrawqtoptions.cpp \
		dcrimage.cpp moc_dcrawqt.cpp \
		moc_dcrawqtoptions.cpp \
		moc_dcrimage.cpp
OBJECTS       = dcrawqt.o \
		dcraw.o \
		dcrawqtoptions.o \
		dcrimage.o \
		moc_dcrawqt.o \
		moc_dcrawqtoptions.o \
		moc_dcrimage.o
DIST          = /opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf \
		DcRawQT.pro
QMAKE_TARGET  = DcRawQT
DESTDIR       = 
TARGET        = libDcRawQT.so.1.0.0
TARGETA       = libDcRawQT.a
TARGETD       = libDcRawQT.so.1.0.0
TARGET0       = libDcRawQT.so
TARGET1       = libDcRawQT.so.1
TARGET2       = libDcRawQT.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET): ui_dcrawqtoptions.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA): ui_dcrawqtoptions.h $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: DcRawQT.pro  /opt/qtsdk-2010.01/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.01/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.01/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile DcRawQT.pro
/opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.01/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.01/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile DcRawQT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DcRawQT1.0.0 || $(MKDIR) .tmp/DcRawQT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DcRawQT1.0.0/ && $(COPY_FILE) --parents dcrawqt.h dcraw.h dcrawqtoptions.h dcrawqt_global.h dcrimage.h .tmp/DcRawQT1.0.0/ && $(COPY_FILE) --parents dcrawqt.cpp dcraw.cpp dcrawqtoptions.cpp dcrimage.cpp .tmp/DcRawQT1.0.0/ && $(COPY_FILE) --parents dcrawqtoptions.ui .tmp/DcRawQT1.0.0/ && (cd `dirname .tmp/DcRawQT1.0.0` && $(TAR) DcRawQT1.0.0.tar DcRawQT1.0.0 && $(COMPRESS) DcRawQT1.0.0.tar) && $(MOVE) `dirname .tmp/DcRawQT1.0.0`/DcRawQT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DcRawQT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dcrawqt.cpp moc_dcrawqtoptions.cpp moc_dcrimage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dcrawqt.cpp moc_dcrawqtoptions.cpp moc_dcrimage.cpp
moc_dcrawqt.cpp: dcraw.h \
		dcrawqt_global.h \
		dcrawqt.h
	/opt/qtsdk-2010.01/qt/bin/moc $(DEFINES) $(INCPATH) dcrawqt.h -o moc_dcrawqt.cpp

moc_dcrawqtoptions.cpp: dcrawqt_global.h \
		dcrawqtoptions.h
	/opt/qtsdk-2010.01/qt/bin/moc $(DEFINES) $(INCPATH) dcrawqtoptions.h -o moc_dcrawqtoptions.cpp

moc_dcrimage.cpp: dcraw.h \
		dcrawqt.h \
		dcrawqt_global.h \
		dcrimage.h
	/opt/qtsdk-2010.01/qt/bin/moc $(DEFINES) $(INCPATH) dcrimage.h -o moc_dcrimage.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dcrawqtoptions.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dcrawqtoptions.h
ui_dcrawqtoptions.h: dcrawqtoptions.ui
	/opt/qtsdk-2010.01/qt/bin/uic dcrawqtoptions.ui -o ui_dcrawqtoptions.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

dcrawqt.o: dcrawqt.cpp dcrawqt.h \
		dcraw.h \
		dcrawqt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcrawqt.o dcrawqt.cpp

dcraw.o: dcraw.cpp dcrawqt_global.h \
		dcraw.h \
		dcrawqt.h \
		dcrimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcraw.o dcraw.cpp

dcrawqtoptions.o: dcrawqtoptions.cpp dcrawqtoptions.h \
		dcrawqt_global.h \
		ui_dcrawqtoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcrawqtoptions.o dcrawqtoptions.cpp

dcrimage.o: dcrimage.cpp dcrimage.h \
		dcraw.h \
		dcrawqt.h \
		dcrawqt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dcrimage.o dcrimage.cpp

moc_dcrawqt.o: moc_dcrawqt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcrawqt.o moc_dcrawqt.cpp

moc_dcrawqtoptions.o: moc_dcrawqtoptions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcrawqtoptions.o moc_dcrawqtoptions.cpp

moc_dcrimage.o: moc_dcrimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dcrimage.o moc_dcrimage.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

